In [0]:
Read the dataset
2. Drop the columns which are unique for all users like IDs (2.5 points)
3. Distinguish the feature and target set (2.5 points)
4. Divide the data set into train and test sets
5. Normalize the train and test data (2.5 points)
6. Initialize & build the model (10 points)
7. Optimize the model (5 points)
9. Predict the results using 0.5 as a threshold (5 points)
Print the Accuracy score and confusion matrix (2.5 points)

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
import pandas as pd
import numpy as np

In [0]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


In [0]:
import tensorflow as tf

In [0]:
tf.__version__

'2.1.0-rc1'

In [0]:
import keras

Using TensorFlow backend.


In [0]:
df=pd.read_csv('gdrive/My Drive/Colab Notebooks/bank.csv')

In [0]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
df.describe()

RowNumber    CustomerId  ...  EstimatedSalary        Exited
count  10000.00000  1.000000e+04  ...     10000.000000  10000.000000
mean    5000.50000  1.569094e+07  ...    100090.239881      0.203700
std     2886.89568  7.193619e+04  ...     57510.492818      0.402769
min        1.00000  1.556570e+07  ...        11.580000      0.000000
25%     2500.75000  1.562853e+07  ...     51002.110000      0.000000
50%     5000.50000  1.569074e+07  ...    100193.915000      0.000000
75%     7500.25000  1.575323e+07  ...    149388.247500      0.000000
max    10000.00000  1.581569e+07  ...    199992.480000      1.000000

[8 rows x 11 columns]

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [0]:
df=df.drop('RowNumber',axis=1)

In [0]:
df=df.drop('Surname',axis=1)

In [0]:
df=df.drop('CustomerId',axis=1)

In [0]:
df.head()

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [0]:
X = df.iloc[:, df.columns != "Exited"]
y = df["Exited"]

In [0]:
X

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0             619    France  Female  ...          1               1        101348.88
1             608     Spain  Female  ...          0               1        112542.58
2             502    France  Female  ...          1               0        113931.57
3             699    France  Female  ...          0               0         93826.63
4             850     Spain  Female  ...          1               1         79084.10
...           ...       ...     ...  ...        ...             ...              ...
9995          771    France    Male  ...          1               0         96270.64
9996          516    France    Male  ...          1               1        101699.77
9997          709    France  Female  ...          0               1         42085.58
9998          772   Germany    Male  ...          1               0         92888.52
9999          792    France  Female  ...          1               0         38190.78

[10000 rows x 10 columns]

In [0]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [0]:
X_train.shape

(7000, 10)

In [0]:
X_test.shape

(3000, 10)

In [0]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler() 

In [0]:
num_features = ["CreditScore", "Age", "Balance",'EstimatedSalary']

X_train_scaled = pd.DataFrame(data = X_train)
X_train_scaled[num_features] = scaler.fit_transform(X_train[num_features])

X_test_scaled = pd.DataFrame(data = X_test)
X_test_scaled[num_features] = scaler.fit_transform(X_test[num_features])

In [0]:
X_test_scaled

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
9394     0.478351   Germany  Female  ...          1               1         0.964388
898      0.325773    France  Female  ...          1               0         0.643444
2398     0.703093     Spain  Female  ...          1               1         0.378437
5906     0.872165    France    Male  ...          0               0         0.446659
2343     0.703093   Germany    Male  ...          1               1         0.678265
...           ...       ...     ...  ...        ...             ...              ...
4004     0.340206     Spain  Female  ...          0               1         0.738024
7375     0.564948    France    Male  ...          1               1         0.278862
9307     0.659794    France    Male  ...          1               1         0.837051
8394     0.674227    France    Male  ...          1               1         0.354008
5233     0.754639   Germany  Female  ...          1               1         0.168447

[3000 rows x 10 columns]

In [0]:
X_train_scaled =pd.get_dummies(X_train_scaled)
X_test_scaled =pd.get_dummies(X_test_scaled)

In [0]:
X_test_scaled

CreditScore       Age  ...  Gender_Female  Gender_Male
9394     0.478351  0.229730  ...              1            0
898      0.325773  0.297297  ...              1            0
2398     0.703093  0.324324  ...              1            0
5906     0.872165  0.189189  ...              0            1
2343     0.703093  0.270270  ...              0            1
...           ...       ...  ...            ...          ...
4004     0.340206  0.310811  ...              1            0
7375     0.564948  0.797297  ...              0            1
9307     0.659794  0.297297  ...              0            1
8394     0.674227  0.689189  ...              0            1
5233     0.754639  0.418919  ...              1            0

[3000 rows x 13 columns]

In [0]:
from keras.models import Sequential
from keras.layers import Dense

# Initialize Sequential model
model = tf.keras.models.Sequential()

# Normalize input data
model.add(tf.keras.layers.BatchNormalization(input_shape=(13,)))

# Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(10,activation='sigmoid'))

In [0]:
# Comile the model
model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [0]:
model.fit(X_train_scaled, y_train, validation_data=(X_test_scaled, y_test), epochs=50,
          batch_size = X_train_scaled.shape[0])

Train on 7000 samples, validate on 3000 samples
Epoch 1/50
7000/7000 [==============================] - 0s 3us/sample - loss: 2.3204 - accuracy: 0.0490 - val_loss: 3.2794 - val_accuracy: 0.0413
Epoch 2/50
7000/7000 [==============================] - 0s 3us/sample - loss: 2.3174 - accuracy: 0.0493 - val_loss: 3.2497 - val_accuracy: 0.0420
Epoch 3/50
7000/7000 [==============================] - 0s 3us/sample - loss: 2.3145 - accuracy: 0.0497 - val_loss: 3.2214 - val_accuracy: 0.0420
Epoch 4/50
7000/7000 [==============================] - 0s 3us/sample - loss: 2.3116 - accuracy: 0.0504 - val_loss: 3.1944 - val_accuracy: 0.0420
Epoch 5/50
7000/7000 [==============================] - 0s 3us/sample - loss: 2.3087 - accuracy: 0.0516 - val_loss: 3.1685 - val_accuracy: 0.0423
Epoch 6/50
7000/7000 [==============================] - 0s 3us/sample - loss: 2.3058 - accuracy: 0.0520 - val_loss: 3.1437 - val_accuracy: 0.0423
Epoch 7/50
7000/7000 [==============================] - 0s 3us/sample - loss

In [0]:
opt=tf.keras.optimizers.SGD(lr=0.001)
model_opt=tf.keras.models.Sequential()

# Normalize input data
model_opt.add(tf.keras.layers.BatchNormalization(input_shape=(13,)))

# Add Dense layer for prediction - Keras declares weights and bias automatically
model_opt.add(tf.keras.layers.Dense(10,activation='softmax'))
# Comile the model
model_opt.compile(optimizer=opt, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [0]:
model_opt.fit(X_train_scaled, y_train, validation_data=(X_test_scaled, y_test))

Train on 7000 samples, validate on 3000 samples
7000/7000 [==============================] - 1s 124us/sample - loss: 2.6999 - accuracy: 0.1414 - val_loss: 2.2857 - val_accuracy: 0.2107


In [0]:
optsgd=tf.keras.optimizers.SGD(lr=0.001)
model_opt_3=tf.keras.models.Sequential()

model_opt_3.add(tf.keras.layers.BatchNormalization(input_shape=(13,)))
# Normalize the data
#model_opt_3.add(tf.keras.layers.BatchNormalization())
# Add Dense layer for prediction - Keras declares weights and bias automatically
model_opt_3.add(tf.keras.layers.Dense(100,activation='sigmoid'))
model_opt_3.add(tf.keras.layers.Dense(100,activation='sigmoid'))
model_opt_3.add(tf.keras.layers.Dense(10,activation='softmax'))
# Comile the model
model_opt_3.compile(optimizer=optsgd, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [0]:
model_opt_3.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization_4 (Batch (None, 13)                52        
_________________________________________________________________
dense_4 (Dense)              (None, 100)               1400      
_________________________________________________________________
dense_5 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_6 (Dense)              (None, 10)                1010      
Total params: 12,562
Trainable params: 12,536
Non-trainable params: 26
_________________________________________________________________


In [0]:
model_opt.fit(X_train_scaled, y_train, validation_data=(X_test_scaled, y_test))

Train on 7000 samples, validate on 3000 samples
7000/7000 [==============================] - 0s 63us/sample - loss: 2.4089 - accuracy: 0.2069 - val_loss: 2.2357 - val_accuracy: 0.2380


In [0]:
score, acc=model.evaluate(X_train_scaled,y_train,batch_size=10)
print('score:',score)
print('acc:',acc)

7000/7000 [==============================] - 1s 104us/sample - loss: 2.5505 - accuracy: 0.0497
score: 2.5505497983523777
acc: 0.049714286


In [0]:
y_pred=np.where(model.predict(X_test_scaled)>0.5,1,0)
print(y_pred)

[[0 1 1 ... 1 1 1]
 [0 1 0 ... 0 1 0]
 [0 1 1 ... 1 0 1]
 ...
 [0 1 0 ... 0 0 1]
 [0 1 1 ... 1 0 1]
 [1 1 1 ... 0 0 1]]


In [0]:
score, acc=model.evaluate(X_test_scaled,y_test,batch_size=10)
print('score:',score)
print('acc:',acc)

3000/3000 [==============================] - 0s 107us/sample - loss: 2.5461 - accuracy: 0.0483
score: 2.5460874780019123
acc: 0.048333332
